language: cpp
compiler:
  - clang
  - gcc
sudo: require
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libstdc++-4.9-dev
    - autoconf
    - automake
    - autotools-dev
    - libtool
#    - libgnutls-dev
    - libconfuse-dev
before_install:
  - $CC --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CC --version
#  - sudo apt-get install nettle-dev
before_script:
  - cd src/contrib
  - ./install_nettle.sh
  - ./install_gnutls.sh
  - ./install_libuci.sh
  - cd ..
script:
  - cd capwap
  - make
  - cd ..
  - cd wtp
  - make
  - cd ..
  - cd ac
  - make
  - ./actube 
